apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    apps: nginx
spec:
  containers:
  - name: nginx
    image: ajeshpk123/ajesh:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
